/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Professor E12 (https://sketchfab.com/Professer_E12_archives)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bluestreak-weapons-aea9542cebc54e2c9ccfa02c650ff6f0
Title: Bluestreak Weapons
*/
"use client";

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

const Weapons = React.memo(function Weapons(props) {
    const { nodes, materials } = useGLTF('/models/bluestreak_weapons.glb');
    const modelRef = useRef();

    useFrame(() => {
        modelRef.current.rotation.y += 0.01;
    });
    return (
        <group {...props}
            dispose={null}
            scale={[0.3, 0.3, 0.3]}
            position={[0, -0.01, 0]}
            ref={modelRef}>
            <group position={[-2.008, 0, 0]}>
                <primitive object={nodes.GLTF_created_1_rootJoint} />
                <skinnedMesh
                    geometry={nodes.Object_38.geometry}
                    material={materials.WEP_Cudgel}
                    skeleton={nodes.Object_38.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.Object_39.geometry}
                    material={materials.WEP_Cudgel_CH}
                    skeleton={nodes.Object_39.skeleton}
                />
            </group>
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh
                geometry={nodes.Object_7.geometry}
                material={materials.WEP_Proxima}
                skeleton={nodes.Object_7.skeleton}
            />
            <skinnedMesh
                geometry={nodes.Object_8.geometry}
                material={materials.WEP_Proxima_CH}
                skeleton={nodes.Object_8.skeleton}
            />
        </group>
    )
});

export default Weapons;
useGLTF.preload("/models/bluestreak_weapons.glb");

